---
title: "Model to Viktor's diet weighting"
author: "Max Lindmark"
date: today
date-format: iso
toc: true
format: 
  html:
    page-layout: full
    embed-resources: true
knitr: 
  opts_chunk:
    fig.align: center
    out-width: 100%
editor: source
---

## Intro

Fit a Tweedie biomass density models and save for viktor.

## Load packages & source functions

```{r load libraries}
#| message: false
#| warning: false

# Load libraries, install if needed
pkgs <- c("tidyverse", "readxl", "tidylog", "RCurl", "devtools", "here", "sdmTMBextra") 

if(length(setdiff(pkgs,rownames(installed.packages()))) > 0){

    install.packages(setdiff(pkgs, rownames(installed.packages())), dependencies = T)
  
  }

invisible(lapply(pkgs, library, character.only = T))

# Packages not on CRAN or dev version
# remotes::install_github("pbs-assess/sdmTMB", dependencies = TRUE)
library(sdmTMB)

# Set path
home <- here::here()
```

## Read data

```{r read data}
# Read data
d <- readr::read_csv(paste0(home, "/data/clean/catch_clean.csv")) %>%
  rename(X = x, Y = y) %>% 
  mutate(density = cod_adult + cod_juvenile) %>% 
  drop_na(depth, temp, oxy, sal, density)
```

## Scale variables

```{r}
d <- d %>% 
  mutate(temp_sc = as.vector(scale(temp)),
         temp_sq = temp_sc^2,
         oxy_sc = as.vector(scale(oxy)),
         oxy_sq = oxy_sc^2,
         sal_sc = as.vector(scale(sal)),
         depth_sc = as.vector(scale(depth)),
         depth_sq = depth_sc*depth_sc) %>%
  mutate(quarter_f = as.factor(quarter),
         year_f = as.factor(year)) %>% 
  ungroup()
```

## Fit models and save AIC

Fit models!

```{r fit models}
mesh <- make_mesh(d, xy_cols = c("X", "Y"), cutoff = 15) # Need specific meshes because not for all hauls did we record all species
    
ggplot() +
  inlabru::gg(mesh$mesh) +
  coord_fixed() +
  geom_point(aes(X, Y), data = d, alpha = 0.2, size = 0.5) +
  annotate("text", -Inf, Inf, label = paste("n knots = ", mesh$mesh$n), hjust = -0.1, vjust = 2) + 
  labs(x = "Easting (km)", y = "Northing (km)")

m3 <- sdmTMB(density ~ 0 + year_f + quarter_f + sal_sc + depth_sc + depth_sq + temp_sc + temp_sq + breakpt(oxy_sc),
             data = d,
             mesh = mesh,
             family = tweedie(link = "log"),
             #family = delta_gamma(),
             spatiotemporal = "IID",
             spatial = "off",
             spatial_varying = ~0 + quarter_f,
             time = "year")
sanity(m3)
d$m3_res <- residuals(m3, model = 1)
#d$m3_res2 <- residuals(m3, model = 2)

qqnorm(d$m3_res); qqline(d$m3_res)
#qqnorm(filter(d, is.finite(m3_res2))$m3_res2); qqline(filter(d, is.finite(m3_res2))$m3_res2)#; xlim(-10, 10); ylim(-10, 10)

# Save stuff
saveRDS(m3, paste0(home, "/R/supp-analysis/viktor/m3.rds"))

d_stat <- d %>% 
  mutate(sal_mean = mean(sal),
         sal_sd = sd(sal),
         oxy_mean = mean(oxy),
         oxy_sd = sd(oxy),
         temp_mean = mean(temp),
         temp_sd = sd(temp))
           
write_csv(d_stat, paste0(home, "/R/supp-analysis/viktor/data_stats.csv"))
```

